//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen1_Parte2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas_credito
    {
        public int id { get; set; }
        public string numeroFactura { get; set; }
        public int mes { get; set; }
        public decimal monto { get; set; }
    }
}
